### ISSUE TITLE
VS Extension More Information link is wrong

### ISSUE THREAD

**Issue by MikeCheel** [CodingWithCalvin/VS-OpenBinFolder#2]
Hey great extension and thanks again for creating it. I just noticed that the More Information link in Manage Extension (inside VS 2022) links to your OpenInNotePadPlusPlus project instead of this one. Thought you should know.

**Comment by CalvinAllen** [comment]
Whoops! Thanks for reporting, I'll get it fixed!

**Comment by CalvinAllen** [comment]
Fixed!
